### ISSUE TITLE
not able to stop the retractig movement in the pick and place pipeline

### ISSUE THREAD

**Issue by ron007d** [moveit/moveit_task_constructor#605]
I am currently using the pick and place pipeline of the `moveit task constructor`.

I want to change certain movement in the pipeline.

After moving to the place pose
1. Don't open the gripper.
2. Don't retract.

but if I disable the set retract motion its fetching error.

Tried other method like calculating the robot_tool0 pose based on the object's target pose with the frame_id = "world"

so that I can move the gripper to the pose where the object will be placed.  but not able to get the tf values of the robot_tool0 with the desired object location. I guess I am missing some calculation.

**Comment by rhaschke** [comment]
> I want to change certain movement in the pipeline. After moving to the place pose
> 
> 1. Don't open the gripper.
> 2. Don't retract.

Simply remove the corresponding stages.

> Tried other method like calculating the robot_tool0 pose based on the object's target pose with the frame_id = "world"
> so that I can move the gripper to the pose where the object will be placed. But not able to get the tf values of the robot_tool0 with the desired object location. I guess I am missing some calculation.

I don't understand what you want to do and what you tried. Please clarify.

**Comment by ron007d** [comment]
sorry for giving a very small info.

Currently I am using this task constructor to pick and place a object
https://moveit.github.io/moveit_task_constructor/tutorials/pick-and-place.html

in this I had to pass two objects 
1. object name
2. place pose
and its working from there

the movement is like this
1. It goes over the object
2. approach the object
3. attach the object to the end effector with grippers touch links
4. grasp the object
5. picks the object
6. then its goes over the place position
7. place the object
8. ungrasp the object
9. detach the object from the end effector
10. retract from the position

in this I wanted to stop this last 3 operation
1. ungrasp the object
2. detach
3. and retract

but this all three are combined into the `pymoveit_mtc.stages.Place`.

after `generating place pose`  how can I use those pose to move to that position. 

so I was not able to fix that so I though out this mathematics

```
header: 
  seq: 0
  stamp: 
    secs: 0
    nsecs:         0
  frame_id: "robot1_tool0"
pose: 
  position: 
    x: 4.117445095779876e-09
    y: 8.452217313319532e-09
    z: 0.15000000031112115
  orientation: 
    x: -1.933663352116923e-08
    y: -6.661140770257759e-09
    z: -0.707108080393473
    w: 0.7071054819772353
```

> ### this is the posestamp of the attach object with the frame_id `robot1_tool0` :point_up_2:

```
header: 
  seq: 0
  stamp: 
    secs: 1724403677
    nsecs: 878194093
  frame_id: "base_link"
pose: 
  position: 
    x: 0.2499999950542699
    y: 2.2709854219371554e-10
    z: 0.45000000017410197
  orientation: 
    x: -0.7071054810709814
    y: 0.7071080812997231
    z: -7.608165474450681e-09
    w: 2.082272085122174e-08
```
> ### this is the posestamp of the robot1_tool0 with the frame_id `base_link` :point_up_2:

```
frame_id: "base_link"
pose:
position: 
  x: 0.24999999263314437
  y: -1.0870961284455411e-09
  z: 0.2999999998629808
orientation: 
  x: 1.0000000000000002
  y: -1.2816341960898667e-09
  z: 1.7204706991680041e-09
  w: -3.811717107357996e-10
```  
> ### this is the object pose value with the frame_id `base_link` :point_up_2:

**if I want the `target pose of the object` to be**
```
frame_id : "base_link"
position: 
  x: 0.24999999263314437
  y: 1.3
  z: 0.0045
orientation: 
  x: -0.707
  y: 0.707
  z: 0.0
  w: 0.0
```
**with the frame_id `base_link`**

> ### then what will be the robot_tool0 pose with the frame_id `base_link`, which can be used to `set target pose`. :point_up_2:
