### ISSUE TITLE
Duplicate planning scene msgs in solution

### ISSUE THREAD

**Issue by captain-yoshi** [moveit/moveit_task_constructor#638]
I think part of #432 introduced the redundant msgs.

Setting a planning scene in the `FixedState` stage results in having identical scene msgs when filling the solution :
```yaml
# Solution.msg
task_id
start_scene                           # identical
sub_trajectory[0]: scene_diff         # identical (should be empty because the FixedState scene is stored in the start_scene ?)
sub_trajectory[1]: scene_diff         # OK real diff
```

**Comment by captain-yoshi** [comment]
Example with an object in the scene, the start scene world is the same as the first diff scene from the first sub trajectory.

Also should the sub trajectories `scene_diff` parameters be all real diff's ?

Start scene
```yaml
name: (noname)
robot_state: ...
world: 
  collision_objects[]
    collision_objects[0]: 
        header: 
        seq: 0
        stamp: 0.000000000
        frame_id: base
      pose: 
        position: 
          x: 0
          y: 0
          z: 0
        orientation: 
          x: 0
          y: 0
          z: 0
          w: 1
      id: sphere
      type: 
        key: 
        db: 
      primitives[]
        primitives[0]: 
                type: 2
          dimensions[]
            dimensions[0]: 0.01
      primitive_poses[]
        primitive_poses[0]: 
                position: 
            x: 0
            y: 0
            z: 0
          orientation: 
            x: 0
            y: 0
            z: 0
            w: 1
      meshes[]
      mesh_poses[]
      planes[]
      plane_poses[]
      subframe_names[]
      subframe_poses[]
      operation: 0
  octomap: ...

is_diff: 0
```

Scene Diff of first sub trajectory
```yaml
name: (noname)
robot_state: ...
world: 
  collision_objects[]
    collision_objects[0]: 
        header: 
        seq: 0
        stamp: 0.000000000
        frame_id: base
      pose: 
        position: 
          x: 0
          y: 0
          z: 0
        orientation: 
          x: 0
          y: 0
          z: 0
          w: 1
      id: sphere
      type: 
        key: 
        db: 
      primitives[]
        primitives[0]: 
                type: 2
          dimensions[]
            dimensions[0]: 0.01
      primitive_poses[]
        primitive_poses[0]: 
                position: 
            x: 0
            y: 0
            z: 0
          orientation: 
            x: 0
            y: 0
            z: 0
            w: 1
  octomap: ...
is_diff: 0

```
